### ISSUE TITLE
Todo list 5

### ISSUE THREAD

**Issue by xulihang** [xulihang/BasicCAT#20]
- [ ] Filter settings (priority, options)
- [ ] Use stemmer to create TM/Term databases' index and process query
- [ ] QA check 
- [ ] Better interative translation prediction (utilizing Chinese words segmentation, bilingual dictionaries)
- [ ] Terms should also sync in git repo
